name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: set up
      run: mkdir build
    - name: cmake
      run: cd build && cmake .. && make
    - name: make check
      run: cd build && make check
   # - name: make distcheck
    #  run: make distcheck
